### ISSUE TITLE
travis failing for tests

### ISSUE THREAD

**Issue by pratapvardhan** [sanand0/xmljson#2]
https://travis-ci.org/sanand0/xmljson/jobs/80951823

```

======================================================================
ERROR: test_etree (tests.test_xmljson.TestBadgerFish)
BadgerFish conversion from data to etree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 77, in test_etree
    eq({'x': 'a'}, '<x><a/></x>')
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 42, in assertEqual
    self.assertEqual(decode(tostring(left)), ''.join(right))
  File "lxml.etree.pyx", line 3236, in lxml.etree.tostring (src/lxml/lxml.etree.c:71960)
TypeError: Type 'Element' cannot be serialized.
======================================================================
ERROR: test_etree (tests.test_xmljson.TestGData)
GData conversion from etree to data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 232, in test_etree
    eq({'x': 'a'}, '<x><a/></x>')
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 42, in assertEqual
    self.assertEqual(decode(tostring(left)), ''.join(right))
  File "lxml.etree.pyx", line 3236, in lxml.etree.tostring (src/lxml/lxml.etree.c:71960)
TypeError: Type 'Element' cannot be serialized.
======================================================================
ERROR: test_etree (tests.test_xmljson.TestParker)
Parker conversion from data to etree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 151, in test_etree
    eq({'x': 'a'}, '<x>a</x>')
  File "/home/travis/build/sanand0/xmljson/tests/test_xmljson.py", line 42, in assertEqual
    self.assertEqual(decode(tostring(left)), ''.join(right))
  File "lxml.etree.pyx", line 3236, in lxml.etree.tostring (src/lxml/lxml.etree.c:71960)
TypeError: Type 'Element' cannot be serialized.
----------------------------------------------------------------------
Ran 15 tests in 0.010s
FAILED (errors=3)
```

**Comment by sanand0** [comment]
Fixed by 1fbb662 -- v0.1.2
